'use client';
import {useEffect,useRef,useState} from 'react';
import Image from 'next/image';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {gsap} from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import Lenis from 'lenis';
import data from './content.json';
const photos:Record<string,string>={'friends-lights':'roice and her friend laughing together beneath outdoor string lights','lab-bench':'roice holding a pipette at bench 2 in the hopkins laboratory','hopkins-podium':'roice presenting at the johns hopkins bloomberg school of public health podium','hopkins-talk':'roice presenting ev-d68 growth curves','hopkins-poster':'roice beside her ev-d68 research poster','aiche-poster':'roice presenting alginate capsule research at aiche','stanford':'roice with certificates in front of hoover tower at stanford','htcc':'roice at the htcc research conference','mxe-team':'medxengineering members collaborating around a table','friends-icecream':'roice and friends enjoying ice cream','friends-night-1':'roice and a friend talking outdoors at night','friends-night-2':'roice outdoors in the evening','vtsi-cohort':'roice with colleagues from the pekosz lab','ptk-officers':'phi theta kappa officers with their chapter certificate','nyc':'roice at joe’s pizza in new york city','commencement':'graduates at msjc commencement','mxe-classroom':'medxengineering members building prosthetic hands together in a classroom','mxe-parts':'3d-printed prosthetic hand parts from a medxengineering build session','mxe-prosthetic':'a 3d-printed prosthetic finger designed by medxengineering','ptk-award':'roice and phi theta kappa officers celebrating their chapter award','embermore-pumpkins':'roice and embermore volunteers with a cart of pumpkins of hope for loma linda children’s hospital','conference-friends':'friends together after a conference presentation','friends-food':'three friends sharing a casual food break','ptk-award-selfie':'phi theta kappa members celebrating together','rollers':'roice in hair rollers on the way to an event','dance-awards':'two dancers celebrating with their trophies','pageant-night':'friends celebrating together at a pageant','graduation-hood':'roice receiving her graduation hood','awards-spread':'a graduation portrait surrounded by awards and honors','graduation-stage':'roice and family together on the graduation stage','mxe-arduino':'medxengineering members wiring motors and an arduino controller','friends-piano':'friends making music together at a piano','mxe-hand':'medxengineering members assembling a 3d-printed prosthetic hand','embermore-cards':'embermore volunteers writing cards together outdoors'};
const CHORUS_S=91;
const SONG_VIDEO='46IM2--jn8Y';
const EMBERMORE_URL='https://embermore.netlify.app/';
function Photo({name,className=''}:{name:string,className?:string}){return <Image unoptimized className={className} src={'/photos/'+name+'.jpg'} alt={photos[name]||'friends at hopkins'} loading="lazy" width={1000} height={1200} placeholder="blur" blurDataURL="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxIiBoZWlnaHQ9IjEiPjxyZWN0IHdpZHRoPSIxIiBoZWlnaHQ9IjEiIGZpbGw9IiMzYjQyNTUiLz48L3N2Zz4="/>}
function PhotoReel({names,onOpen,label}:{names:string[],onOpen:(name:string)=>void,label:string}){
 const viewport=useRef<HTMLDivElement>(null);const [index,setIndex]=useState(0);const [paused,setPaused]=useState(false);const [visible,setVisible]=useState(false);
 useEffect(()=>{if(!viewport.current)return;const io=new IntersectionObserver(entries=>setVisible(entries[0].isIntersecting),{threshold:.35});io.observe(viewport.current);return()=>io.disconnect()},[]);
 function go(i:number){const el=viewport.current;if(!el)return;el.scrollTo({top:el.clientHeight*i,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}
 useEffect(()=>{if(paused||!visible||names.length<2||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const id=setInterval(()=>{if(!document.hidden)go((index+1)%names.length)},4300);return()=>clearInterval(id)},[paused,visible,index,names.length]);
 return <div className="photo-reel" onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)} onFocusCapture={()=>setPaused(true)} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget))setPaused(false)}}><div className="photo-reel-viewport" ref={viewport} data-lenis-prevent onScroll={()=>{const el=viewport.current;if(el)setIndex(Math.round(el.scrollTop/el.clientHeight))}} aria-label={label+' photographs; scroll vertically'}>{names.map(name=><button key={name} className="photo-reel-slide" onClick={()=>onOpen(name)} aria-label={'enlarge '+(photos[name]||name)}><Photo name={name}/><span className="editorial-view">closer look ↗</span></button>)}</div><div className="reel-photo-controls"><span>{String(index+1).padStart(2,'0')} / {String(names.length).padStart(2,'0')}</span>{names.length>1&&<div><button onClick={()=>go(Math.max(0,index-1))} disabled={index===0} aria-label={'previous '+label+' photo'}>↑</button><button onClick={()=>go(Math.min(names.length-1,index+1))} disabled={index===names.length-1} aria-label={'next '+label+' photo'}>↓</button></div>}</div></div>
}
function GalleryGrid({names,onOpen,captions}:{names:string[],onOpen:(name:string)=>void,captions?:Record<string,string>}){
 return <div className="vsco-grid">{names.map((name,i)=><figure key={name} className={'vsco-item vsco-'+i%5}><button className="modal-photo-button" onClick={()=>onOpen(name)} aria-label={'enlarge '+photos[name]}><Photo name={name}/></button><figcaption>{captions?.[name]||'caption to come.'}</figcaption></figure>)}</div>
}
const humanPics=['friends-lights','friends-icecream','friends-night-1','friends-night-2','vtsi-cohort','ptk-officers','nyc','friends-food','rollers','friends-piano'];
const humanCaptions:Record<string,string>={'friends-lights':'under the lights','friends-icecream':'ice cream after lab!','friends-night-1':'late nights','friends-night-2':'the best conversations','vtsi-cohort':'my vtsi cohort at hopkins!','ptk-officers':'ptk officers, five-star chapter!','nyc':'i survived my trip to nyc!'};
const motif=['D4','A4','B4','C5','E5'];
const whiteNotes=['C4','D4','E4','F4','G4','A4','B4','C5','D5','E5','F5','G5','A5','B5'];
export default function Home(){const root=useRef<HTMLDivElement>(null);const [modal,setModal]=useState<string|null>(null);const [menu,setMenu]=useState(false);const [sound,setSound]=useState(false);const soundRef=useRef(false);const pianoContext=useRef<AudioContext|null>(null);const [active,setActive]=useState('');const widget=useRef<any>(null);const playerHost=useRef<HTMLDivElement>(null);const widgetReady=useRef(false);const songStarted=useRef(false);const chorusPending=useRef(true);const volumeFade=useRef<ReturnType<typeof setInterval>|null>(null);const [songStatus,setSongStatus]=useState('ready');const [playing,setPlaying]=useState(false);const [polaroid,setPolaroid]=useState(0);const [photoPaused,setPhotoPaused]=useState(false);const [photoHover,setPhotoHover]=useState(false);const [coffeeProgress,setCoffeeProgress]=useState(0);const songAutoAttempted=useRef(false);const songRequested=useRef(false);const [pianoError,setPianoError]=useState(false);const [spin,setSpin]=useState(0);const touchStart=useRef(0);const [lightbox,setLightbox]=useState<string|null>(null);const [zoom,setZoom]=useState(false);const [isSpinning,setIsSpinning]=useState(true);

const conferencePics=['ptk-award','conference-friends','ptk-award-selfie','dance-awards','pageant-night','graduation-hood','awards-spread','graduation-stage','hopkins-podium','hopkins-talk','hopkins-poster','aiche-poster','stanford','htcc'];
const mxePics=['mxe-team','mxe-classroom','mxe-parts','mxe-prosthetic','mxe-arduino','mxe-hand'];
const embermorePics=['embermore-pumpkins','embermore-cards'];
const buildPics=[...mxePics,...embermorePics];
const buildExtras:Record<string,{pics:string[],link?:string}>={'medxengineering':{pics:mxePics},'embermore foundation':{pics:embermorePics,link:EMBERMORE_URL}};
const zoomPhotos=[...humanPics,...conferencePics,...buildPics];
function openPhoto(name:string){setZoom(false);setLightbox(name)}
function stepPhoto(step:number){setZoom(false);setLightbox(name=>zoomPhotos[(zoomPhotos.indexOf(name||'')+step+zoomPhotos.length)%zoomPhotos.length])}
function spinMachine(){if(isSpinning)return;setIsSpinning(true);setSpin(v=>v+1)}
useEffect(()=>{const id=setTimeout(()=>setIsSpinning(false),2700);return()=>clearTimeout(id)},[spin]);
useEffect(()=>{if(!lightbox)return;const handler=(e:KeyboardEvent)=>{if(e.key==='ArrowRight'){e.preventDefault();stepPhoto(1)}if(e.key==='ArrowLeft'){e.preventDefault();stepPhoto(-1)}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[lightbox]);
const vinylPhotos=['friends-lights','friends-night-1','friends-icecream','friends-night-2','hopkins-friends','vtsi-cohort','friends-food','rollers','friends-piano'];
const vinylCaptions=['under the lights','tows','ice cream after lab','late nights','my people','after hours','food break','on the way','a little music'];
function fadeInSong(){
 if(volumeFade.current)clearInterval(volumeFade.current);
 let volume=0;widget.current?.setVolume?.(0);
 volumeFade.current=setInterval(()=>{volume=Math.min(65,volume+5);widget.current?.setVolume?.(volume);if(volume>=65&&volumeFade.current){clearInterval(volumeFade.current);volumeFade.current=null}},220);
}
function requestSong(){
 songRequested.current=true;setSongStatus('loading');
 if(widgetReady.current){if(!songStarted.current){chorusPending.current=true;widget.current.seekTo(CHORUS_S,true)}widget.current.setVolume(0);widget.current.playVideo();}
}
function enable(){
 if(soundRef.current){songAutoAttempted.current=true;songRequested.current=false;if(volumeFade.current)clearInterval(volumeFade.current);widget.current?.pauseVideo?.();soundRef.current=false;setSound(false);setSongStatus('paused')}
 else requestSong();
}
function play(note:string,fromScroll=false){
 setActive(note);setTimeout(()=>setActive(''),350);
 if(fromScroll&&!pianoContext.current)return;
 try{
 const AC=window.AudioContext||(window as any).webkitAudioContext;
 if(!pianoContext.current)pianoContext.current=new AC();
 const ctx=pianoContext.current!;
 const renderNote=()=>{const names:Record<string,number>={C:0,'C#':1,D:2,'D#':3,E:4,F:5,'F#':6,G:7,'G#':8,A:9,'A#':10,B:11};const match=note.match(/^([A-G]#?)([0-9])$/);if(!match)return;const midi=(Number(match[2])+1)*12+names[match[1]];const f=440*Math.pow(2,(midi-69)/12);const now=ctx.currentTime;
 const master=ctx.createGain();master.gain.value=.21;master.connect(ctx.destination);
 [1,2,3,4,5,7].forEach((harmonic,i)=>{const osc=ctx.createOscillator();const envelope=ctx.createGain();osc.type='sine';osc.frequency.value=f*harmonic*(1+harmonic*harmonic*.000035);envelope.gain.setValueAtTime(.00001,now);envelope.gain.exponentialRampToValueAtTime([1,.45,.18,.1,.055,.025][i],now+.006);envelope.gain.exponentialRampToValueAtTime(.00001,now+Math.max(.28,2.2-i*.29));osc.connect(envelope);envelope.connect(master);osc.start(now);osc.stop(now+2.4);osc.onended=()=>{osc.disconnect();envelope.disconnect()}});setTimeout(()=>master.disconnect(),2600);setPianoError(false)};
 if(ctx.state==='suspended'){void ctx.resume().then(renderNote).catch(()=>setPianoError(true))}else renderNote();
 }catch{setPianoError(true)}
}
useEffect(()=>{if(photoPaused||photoHover||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const id=setInterval(()=>setPolaroid(i=>(i+1)%vinylPhotos.length),3200);return()=>clearInterval(id)},[photoPaused,photoHover]);
useEffect(()=>{const el=document.querySelector('.coffee-scene');if(!el)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(!reduced)return;const io=new IntersectionObserver(entries=>{if(entries[0].isIntersecting&&!songAutoAttempted.current){songAutoAttempted.current=true;requestSong()}},{threshold:.3});io.observe(el);return()=>io.disconnect()},[]);
useEffect(()=>{
 let disposed=false;const w_=window as any;
 const stopped=()=>{setPlaying(false);soundRef.current=false;setSound(false)};
 const build=()=>{if(disposed||!playerHost.current)return;const target=document.createElement('div');playerHost.current.replaceChildren(target);
 widget.current=new w_.YT.Player(target,{videoId:SONG_VIDEO,host:'https://www.youtube-nocookie.com',playerVars:{start:CHORUS_S,playsinline:1,rel:0,modestbranding:1,controls:1},events:{
  onReady:(e:any)=>{widgetReady.current=true;e.target.setVolume(0);if(songRequested.current){e.target.seekTo(CHORUS_S,true);e.target.playVideo()}},
  onStateChange:(e:any)=>{const YT=w_.YT.PlayerState;const pl=e.target;
   if(e.data===YT.PLAYING){songRequested.current=true;if(!songStarted.current||chorusPending.current){songStarted.current=true;chorusPending.current=false;if(pl.getCurrentTime()<CHORUS_S-2)pl.seekTo(CHORUS_S,true)}fadeInSong();setPlaying(true);setSongStatus('playing');soundRef.current=true;setSound(true)}
   else if(e.data===YT.PAUSED){songRequested.current=false;stopped();setSongStatus('paused')}
   else if(e.data===YT.ENDED){songRequested.current=false;stopped();setSongStatus('paused');songStarted.current=false;chorusPending.current=true}},
  onError:()=>{stopped();setSongStatus('unavailable')}}})};
 if(w_.YT?.Player)build();else{const prev=w_.onYouTubeIframeAPIReady;w_.onYouTubeIframeAPIReady=()=>{prev?.();build()};if(!document.querySelector('script[src="https://www.youtube.com/iframe_api"]')){const script=document.createElement('script');script.src='https://www.youtube.com/iframe_api';script.async=true;script.onerror=()=>setSongStatus('unavailable');document.head.appendChild(script)}}
 return()=>{disposed=true;if(volumeFade.current)clearInterval(volumeFade.current);try{widget.current?.destroy()}catch{}widget.current=null;widgetReady.current=false}
},[]);

useEffect(()=>{gsap.registerPlugin(ScrollTrigger);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced)return;const lenis=new Lenis({duration:1.1});lenis.on('scroll',ScrollTrigger.update);const tick=(t:number)=>lenis.raf(t*1000);gsap.ticker.add(tick);const ctx=gsap.context(()=>{
 gsap.from('.about-line',{scrollTrigger:{trigger:'#about',start:'top 75%'},y:16,opacity:0,stagger:.15,duration:.8});
 gsap.to('.cabinet',{scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom 25%',scrub:1},scale:.22,y:-220,opacity:0,ease:'power1.in'});
 gsap.fromTo('.site-header',{y:-70,opacity:0},{y:0,opacity:1,scrollTrigger:{trigger:'#about',start:'top 65%',toggleActions:'play none none reverse'},duration:.4});
 gsap.from('.work-row',{scrollTrigger:{trigger:'.work-list',start:'top 85%'},opacity:0,y:20,stagger:.07,duration:.6});
 const piano=gsap.timeline({scrollTrigger:{trigger:'.piano-scene',start:'top top',end:'+=160%',pin:true,scrub:.7}});piano.from('.staff-line',{scaleX:0,transformOrigin:'left',stagger:.05});document.querySelectorAll('.music-note').forEach((n,i)=>{piano.fromTo(n,{opacity:0,y:20},{opacity:1,y:0,duration:.5,onStart:()=>play(motif[i],true)});piano.to(`[data-note="${motif[i]}"]`,{backgroundColor:'#cbbf9e',y:4,duration:.2},'<')});piano.to('.music-note',{y:450,opacity:0,stagger:.1,duration:1});
 const coffee=gsap.timeline({scrollTrigger:{trigger:'.coffee-scene',start:'top top',end:'+=150%',pin:true,scrub:.72,onUpdate:self=>{setCoffeeProgress(self.progress);if(self.progress>.48&&!songAutoAttempted.current){songAutoAttempted.current=true;requestSong()}}}});
 coffee.to('.full-coffee-cup',{x:105,y:76,rotation:94,scale:.9,ease:'power2.inOut',duration:.9},0).to('.full-coffee-cup',{opacity:0,duration:.22},.72).fromTo('.spill-vinyl-art',{opacity:0,scale:.7,rotation:-4},{opacity:1,scale:1,rotation:0,ease:'back.out(1.4)',duration:.7},.62).fromTo('.spinning-spill',{opacity:0,scale:.5},{opacity:1,scale:1,duration:.5},.9).fromTo('.instant-photo-lab',{opacity:0,x:45},{opacity:1,x:0,duration:.65},.85).fromTo('.coffee-controls',{y:12,opacity:0},{y:0,opacity:1,duration:.35},1.15);
},root);return()=>{ctx.revert();lenis.destroy();gsap.ticker.remove(tick)}},[]);
const nav=<>{['about','work','music','say hi'].map(x=><a key={x} href={'#'+x.replace(' ','-')} onClick={()=>setMenu(false)}>{x}</a>)}</>;
return <div ref={root}><header className="site-header"><a href="#top" className="mini-logo" aria-label="roice home">{'ROICE'.split('').map(x=><span key={x}>{x}</span>)}</a><div className="header-right"><nav>{nav}</nav><button className="header-sound" onClick={enable} aria-pressed={sound}>{sound?'music off':'music on'}</button></div><button className="mobile-menu" aria-label="open navigation" onClick={()=>setMenu(true)}>♪</button></header><Dialog open={menu} onOpenChange={setMenu}><DialogContent className="glass-modal menu-modal"><DialogTitle>roice</DialogTitle><DialogDescription className="sr-only">page navigation</DialogDescription>{nav}</DialogContent></Dialog>
<section className="hero" id="top"><div className="arcade-room" aria-hidden="true"><div className="arcade-wall"/><div className="arcade-floor"/><i className="spotlight spotlight-one"/><i className="spotlight spotlight-two"/><div className="retro-sun"/><div className="wall-neon neon-left">lucky<br/>you</div><div className="wall-neon neon-right">777</div><div className="wall-neon neon-top">★ jackpot ★</div><div className="wall-neon neon-bar">bar</div><i className="neon-tube tube-a"/><i className="neon-tube tube-b"/><i className="neon-tube tube-c"/><div className="arcade-haze"/></div><div className="hero-top"><span>roice de castro</span><span>guam / california</span></div><div className={'cabinet '+(isSpinning?'machine-spinning':'machine-won')}><div className="jackpot-bulbs" aria-hidden="true">{Array.from({length:18},(_,i)=><i key={i} style={{left:`${5+i*5.3}%`,animationDelay:`${i*.08}s`}}/>)}</div><div className="side-bulbs side-left" aria-hidden="true">{Array.from({length:14},(_,i)=><i key={i} style={{top:`${4+i*7}%`,animationDelay:`${i*.1}s`}}/>)}</div><div className="side-bulbs side-right" aria-hidden="true">{Array.from({length:14},(_,i)=><i key={i} style={{top:`${4+i*7}%`,animationDelay:`${(13-i)*.1}s`}}/>)}</div><div className="marquee"><span>★</span><span>jackpot</span><span>★</span></div><div className="reels" key={spin}>{'ROICE'.split('').map((x,i)=><div className="reel" key={x}><div className="reel-track" style={{animationDelay:`${i*.3}s`}}><span>7</span><span>★</span><span>BAR</span><span>7</span><span>★</span><span className="neon-letter">{x}</span></div></div>)}</div><div className="cabinet-bottom"><i/><i/><i/></div><div className="luck-panel"><span>lucky you</span><small>knowing me is like winning the lottery.</small></div><div className="coin-tray"><span/><i/></div><div className="arcade-console"><span className="jackpot-caption" aria-live="polite">{isSpinning?'feeling lucky...':'jackpot. you found roice.'}</span><button className="spin-button" onClick={spinMachine} disabled={isSpinning}>{isSpinning?'spinning':'spin again'}</button></div><div className="bling bling-one"/><div className="bling bling-two"/><div className="bling bling-three"/><button className="lever" onClick={spinMachine} disabled={isSpinning} aria-label="spin the roice slot machine again"><span/><i/></button><div className="cabinet-foot"/></div><div className="hero-caption"><p>roice de castro</p><div className="hero-actions"><button onClick={enable} aria-pressed={sound}>{sound?'music off':'music on · chorus ♪'}</button><a href="#about">scroll ↓</a></div></div></section>
<section id="about" className="about section"><div className="eyebrow about-line">01 / a little introduction</div><h1 className="about-line">hi, i'm roice<span>!</span></h1>{data.about.map((line,i)=><p className="about-line" key={i}>{line}</p>)}<aside className="harmonica-corner" aria-label="tiny Plankton running between the sound holes of a harmonica"><img className="harmonica-pixel" src="/art/harmonica.png" alt="pixel-art harmonica viewed from above" width="1200" height="400" loading="lazy"/><div className="plankton-track"><img src="/art/plankton.png" alt="Plankton running frantically" width="70" height="70"/><i className="pixel-breath"/></div></aside></section>
<div className="night"><section id="work" className="section work"><div className="section-heading"><span className="eyebrow">02 / curiosity at work</span><h2>what i've been<br/>up to!</h2></div><div className="work-grid timeline-only"><div className="work-list">{data.work.map(([date,text],i)=><div className="work-row" key={i}><span className="date">{date}</span><p>{text.includes('embermore')?<a className="work-link" href={EMBERMORE_URL} target="_blank" rel="noreferrer">{text} ↗</a>:text}</p></div>)}<a className="pill" href="https://roicedecastro.substack.com" target="_blank" rel="noreferrer">i write on substack! →</a></div></div></section>
<section className="section editorial-gallery"><div className="editorial-heading"><div><span className="eyebrow">03 / the moments in between</span><h2>life outside<br/><em>the lab.</em></h2></div><p>people, projects,<br/>and places along the way.</p></div><p className="gallery-instruction">tap a gallery to open it.</p><div className="editorial-grid"><article className="editorial-card editorial-humans"><PhotoReel names={humanPics} onOpen={openPhoto} label="humans"/><button className="editorial-category" onClick={()=>setModal('humans')}><span className="editorial-card-title"><h3>humans</h3><span>open ↗</span></span><p>everyone else, in no particular order.</p></button></article><article className="editorial-card editorial-talks"><PhotoReel names={conferencePics} onOpen={openPhoto} label="doer"/><button className="editorial-category" onClick={()=>setModal('talks')}><span className="editorial-card-title"><h3>doer.</h3><span>open ↗</span></span><p>talks, awards, conferences, and everything in between.</p></button></article><article className="editorial-card editorial-builds"><PhotoReel names={buildPics} onOpen={openPhoto} label="builds"/><button className="editorial-category" onClick={()=>setModal('builds')}><span className="editorial-card-title"><h3>builds</h3><span>open ↗</span></span><p>hands-on, half-finished, and made together.</p></button></article></div></section>
<section id="music" className="piano-scene scene"><div className="scene-inner"><div className="eyebrow">04 / a different kind of language</div><div className="music-heading"><h2>my name is a melody<span>♪</span></h2><span className="piano-ready">touch a key. make a little music.</span></div><p className="music-fact">fun fact! using the french musical cryptogram (the same trick composers used to spell haydn), r-o-i-c-e becomes d-a-b-c-e.</p><div className="score"><div className="score-label"><span>roice</span><span>roice de castro</span></div><svg viewBox="0 0 900 180" aria-label="sheet music: d4, a4, b4, c5, e5"><g stroke="#aeb6b0" strokeWidth="1">{[50,70,90,110,130].map(y=><path key={y} className="staff-line" d={`M20 ${y}H880`}/>)}</g><text x="28" y="128" fill="#e5e2dd" fontSize="95">𝄞</text>{[140,100,90,80,60].map((y,i)=><g className="music-note" key={i}><ellipse cx={190+i*145} cy={y} rx="12" ry="8" transform={`rotate(-20 ${190+i*145} ${y})`} fill={i===4?'#303432':'#e5e2dd'} stroke="#e5e2dd" strokeWidth="3"/><path d={`M${201+i*145} ${y}V${y-55}`} stroke="#e5e2dd" strokeWidth="3"/>{(i===2||i===3)&&<path d={`M${201+i*145} ${y-55}q25 15 6 34`} fill="none" stroke="#e5e2dd" strokeWidth="3"/>}<text x={181+i*145} y="174" fill="#bec6be" fontSize="19">{'ROICE'[i]}</text>{i===4&&<text x="755" y="25" fill="white" fontSize="26">𝄐</text>}</g>)}</svg></div><div className="keyboard">{whiteNotes.map((n,i)=><div className="key-wrap" key={n}><button data-note={n} className={'white-key '+(active===n?'pressed':'')} onClick={()=>play(n)} aria-label={'play '+n}>{motif.includes(n)?<span>{'ROICE'[motif.indexOf(n)]}</span>:null}<small>{n}</small></button>{![2,6,9,13].includes(i)&&<button className={'black-key '+(active===n.replace(/\d/,'#'+n.slice(-1))?'pressed':'')} aria-label={'play '+n[0]+' sharp '+n.slice(-1)} onClick={()=>play(n[0]+'#'+n.slice(-1))}/>}</div>)}</div><p className="keyboard-hint">{pianoError?'tap a key again to enable audio.':'a little piece of me, in five notes. · always ready to play'}</p></div><div className="rain">{Array.from({length:24},(_,i)=><i key={i} style={{left:`${i*4.3}%`,animationDelay:`${i*.17}s`,animationDuration:`${1.4+i%3*.4}s`}}/>)}</div></section>
<section className="coffee-scene" id="on-repeat"><div className="coffee-topline"><span className="eyebrow">05 / on repeat</span><span>{coffeeProgress<.32?'coffee first.':coffeeProgress<.62?'oops.':'press play.'}</span></div><h2 className="coffee-title">friendly pressure,<br/><em>on repeat.</em></h2><div className="coffee-experience"><div className="spill-stage"><div className="full-coffee-cup" aria-hidden="true"><div className="full-cup-rim"><i/></div><div className="full-cup-body"/><div className="full-cup-handle"/><div className="full-cup-saucer"/><span className="full-steam steam-a"/><span className="full-steam steam-b"/></div><img className="spill-vinyl-art" src="/art/spilled-vinyl-clean.png" alt="a tipped coffee cup spilling into a vinyl record"/><div className={'spinning-spill '+((playing||coffeeProgress>.48)?'is-playing':'')} aria-hidden="true"><i/><span/></div></div><div className="instant-photo-lab" onMouseEnter={()=>setPhotoHover(true)} onMouseLeave={()=>setPhotoHover(false)}><img className="camera-art" src="/art/instant-camera-clean.png" alt="hand-drawn instant camera printing a photograph"/><div className="camera-slot"/><figure className="printing-photo" key={vinylPhotos[polaroid]}><Photo name={vinylPhotos[polaroid]}/><figcaption>{vinylCaptions[polaroid]}</figcaption></figure><button className="printer-pause" onClick={()=>setPhotoPaused(v=>!v)}>{photoPaused?'print next':'pause printer'}</button></div></div><div className="coffee-controls"><button onClick={enable} className="coffee-play" aria-label={playing?'pause music':'play friendly pressure from the chorus'}>{playing?'Ⅱ pause':'▷ play the chorus'}</button><span>{playing?'friendly pressure — into the sunshine edit':'jhelisa / sunship'}</span></div></section>
<section className="photo-player-section section music-player-only" id="photo-player"><div className="photo-player-copy"><span className="eyebrow">still on repeat</span><h2>friendly pressure.</h2><p>press play, or leave it spinning.</p><div className="now-playing"><button className="vinyl-play" onClick={enable} aria-label={playing?'pause song':'play song from the chorus'}>{playing?'Ⅱ':'▷'}</button><div><span>{playing?'now playing':'on the record'}</span><h3>friendly pressure</h3><p>into the sunshine edit</p><small>jhelisa / sunship</small></div></div><div className="song-player" id="vinyl-player" ref={playerHost}/><p className="audio-status" aria-live="polite">{songStatus==='unavailable'?<>player unavailable. <a href="https://www.youtube.com/watch?v=46IM2--jn8Y&t=91s" target="_blank" rel="noreferrer">listen on youtube</a></>:songStatus==='loading'?'if the music has not started, press play in the player above.':'starts at the chorus (1:31)'}</p></div></section>
<footer id="say-hi" className="section footer"><span className="eyebrow">good things start with a conversation.</span><h2>say hi!</h2><div className="contact-links"><a className="pill" href="https://linkedin.com/in/roicedecastro" target="_blank" rel="noreferrer">linkedin ↗</a><a className="pill" href="https://roicedecastro.substack.com" target="_blank" rel="noreferrer">substack ↗</a><a className="pill" href="mailto:0725131@my.msjc.edu">email ↗</a></div><p>also: american red cross disaster volunteer + av tech at st. catherine of alexandria church </p><div className="footer-bottom"><span>made with love from guam </span><span>© 2026 roice de castro</span></div></footer></div>
<Dialog open={!!modal} onOpenChange={o=>!o&&setModal(null)}><DialogContent className="glass-modal gallery-modal" data-lenis-prevent><DialogTitle className="modal-title">{modal==='talks'?'doer.':modal}</DialogTitle><DialogDescription className="modal-description">{modal==='humans'?'people, as they happened.':modal==='talks'?'talks, awards, conferences, and everything in between.':'things made by hand, together.'}</DialogDescription>{modal==='humans'&&<GalleryGrid names={humanPics} onOpen={openPhoto} captions={humanCaptions}/>} {modal==='talks'&&<><GalleryGrid names={conferencePics} onOpen={openPhoto}/><div className="talk-list">{data.talks.map(([title,venue,type],i)=><article key={i}><div><h3>{title}</h3><p>{venue}</p></div><span className={'type '+type}>{type}</span></article>)}</div></>} {modal==='builds'&&<><GalleryGrid names={buildPics} onOpen={openPhoto}/><div className="build-notes">{data.builds.map(([title,desc])=><article className="build-tile" key={title}><h3>{title}</h3><p>{desc}</p>{buildExtras[title]?.link&&<a className="build-link" href={buildExtras[title].link} target="_blank" rel="noreferrer">visit embermore ↗</a>}</article>)}</div></>}</DialogContent></Dialog><Dialog open={!!lightbox} onOpenChange={o=>{if(!o){setLightbox(null);setZoom(false)}}}><DialogContent className="photo-lightbox" data-lenis-prevent><DialogTitle className="sr-only">photograph close-up</DialogTitle><DialogDescription className="lightbox-caption">{lightbox?photos[lightbox]:''}</DialogDescription><div className={'lightbox-image-area '+(zoom?'zoomed':'')} data-lenis-prevent>{lightbox&&<img src={'/photos/'+lightbox+'.jpg'} alt={photos[lightbox]||'photograph'} onClick={()=>setZoom(v=>!v)} width="1500" height="1500"/>}</div><div className="lightbox-controls"><button onClick={()=>stepPhoto(-1)} aria-label="previous photograph">← previous</button><button onClick={()=>setZoom(v=>!v)} aria-pressed={zoom}>{zoom?'fit image':'zoom 2×'}</button><button onClick={()=>stepPhoto(1)} aria-label="next photograph">next →</button></div></DialogContent></Dialog></div>}
